### ISSUE TITLE
Could this data used for other time series signal?

### ISSUE THREAD

**Issue by Like-h** [duanyiqun/DS-DDPM#9]

**Comment by duanyiqun** [comment]
It is a interesting problem. 
I haven't check the ability on time sequence yet. But I think as long as it is a sequence data, theoretically it is ok. But the issue is single sequence might that informative as the EEG is a sequence matrix, it has correlation at each time step. 

Have you try any experiments on time series data? If you got positive results I'm keen to update some details.
